Initial codeowners and maintainers
camaraproject/DedicatedNetworks pull request #4
Opened 2024-10-01 15:50 UTC by tlohmar

#### What type of PR is this?

Add one of the following kinds:
* subproject management

#### What this PR does / why we need it:
sets the intial codeowners and maintainers

#### Which issue(s) this PR fixes:

<!-- Automatically closes linked issue when PR is merged.

Fixes #3

#### Special notes for reviewers:

#### Changelog input

```
 release-note

```

#### Additional documentation 

This section can be blank.

```
docs

```

2024-10-01 16:18 UTC, hdamker commented on MAINTAINERS.MD
> +| Vodafone | Steve Vickers | Maintainer | @SteveV-Vodafone |
Please stay with the given format of the files. Maintainers go here, Codeowners have to go into the CODEOWNERS file. The roles are then implicit given.

```suggestion
| Org                    | Name                                      | GitHub Username        |
| -----------------------| -----------------------------------------| -----------------------|
| Ericsson | Thorsten Lohmar | @tlohmar |
| Nokia | Peter Kovacs | @PeterKovacs2 |
| Telefonica| Jorge Garcia Hospital |  @jgarciahospital |
| Vodafone | Eric Murray | @eric-murray |
| Vodafone | Steve Vickers |  @SteveV-Vodafone |
```

2024-10-01 16:31 UTC, hdamker requested changes
The information has to be distributed to the two files CODEOWNERS (used by GitHub to enforce branch protection) and MAINTAINERS.md (format is consistent across all repositories). I added the update of the CODEOWNERS to the PR and suggested the correct format of MAINTAINERS.md above.

I also invited @PeterKovacs2 and @SteveV-Vodafone to the CAMARA organization. As soon as they have accepted the invitation we can go forward here.

2024-10-01 16:35 UTC, tlohmar reviewed
thx for the correction.

2024-10-07 07:19 UTC, ThorstenL2024 approved these changes
OK

2024-10-07 08:26 UTC, hdamker commented on MAINTAINERS.MD
> +| Vodafone | Steve Vickers | Maintainer | @SteveV-Vodafone |
```suggestion
| Org                   | Name                              |GitHub Username        |
|---------------|------------------------| ----------------------|
| Ericsson | Thorsten Lohmar  | @tlohmar |
| Nokia | Peter Kovacs | @PeterKovacs2 |
| Telefonica| Jorge Garcia Hospital | @jgarciahospital |
| Vodafone | Steve Vickers | @SteveV-Vodafone |
```

2024-10-07 08:27 UTC, merged